## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-express
  name: test-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-express
  template:
    metadata:
      labels:
        app: test-express
    spec:
      containers:
      - image: bitnami/express
        name: express
